GET http://127.0.0.1:5000/posts HTTP/1.1
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZG9uZGkifQ.EFnp35PkdepquIkSdwOqoMvfd2nBwV3eP8xNPZIFuzg

###

POST http://127.0.0.1:5000/posts HTTP/1.1
content-type: application/json
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZG9uZGkifQ.EFnp35PkdepquIkSdwOqoMvfd2nBwV3eP8xNPZIFuzg

{
    "user_id": 2,
    "post": "meu "
}

###

PATCH  http://127.0.0.1:5000/posts/1 HTTP/1.1
content-type: application/json
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZG9uZGkifQ.EFnp35PkdepquIkSdwOqoMvfd2nBwV3eP8xNPZIFuzg

{
    "user_id": 2,
    "post": "fadfgkljihsedgrf"
}

###

DELETE  http://127.0.0.1:5000/posts/1
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZG9uZGkifQ.EFnp35PkdepquIkSdwOqoMvfd2nBwV3eP8xNPZIFuzg
